[server]
port = 8055
host = 0.0.0.0
; url_prefix = /baihu
message_server = http://message-nest-demo-site.qwapi.eu.org/
pprof_enabled=true


[database]
; type = sqlite
type = mysql
host = app.engigu.cn
port = 33066
user = root
password = Gq19940507+****+
dbname = baihu-test2
table_prefix = baihu_
; debug = true

[security]
secret = baihu_secret_key_change_me
